
import { Word } from './types';

export const INITIAL_WORDS: Word[] = [
  { id: 'word_001', hungarian: 'alma', japanese: 'りんご', example: { sentence: 'Az alma piros.', translation: 'そのリンゴは赤いです。' } },
  { id: 'word_002', hungarian: 'kutya', japanese: '犬', example: { sentence: 'A kutya ugat.', translation: '犬が吠えています。' } },
  { id: 'word_003', hungarian: 'ház', japanese: '家', example: { sentence: 'Ez egy nagy ház.', translation: 'これは大きな家です。' } },
  { id: 'word_004', hungarian: 'könyv', japanese: '本', example: { sentence: 'Olvasok egy könyvet.', translation: '私は本を読んでいます。' } },
  { id: 'word_005', hungarian: 'asztal', japanese: 'テーブル', example: { sentence: 'A könyv az asztalon van.', translation: '本はテーブルの上にあります。' } },
  { id: 'word_006', hungarian: 'szék', japanese: '椅子' },
  { id: 'word_007', hungarian: 'víz', japanese: '水' },
  { id: 'word_008', hungarian: 'kenyér', japanese: 'パン' },
  { id: 'word_009', hungarian: 'autó', japanese: '車' },
  { id: 'word_010', hungarian: 'város', japanese: '街' },
  { id: 'word_011', hungarian: 'utca', japanese: '通り' },
  { id: 'word_012', hungarian: 'iskola', japanese: '学校' },
  { id: 'word_013', hungarian: 'tanuló', japanese: '学生' },
  { id: 'word_014', hungarian: 'tanár', japanese: '先生' },
  { id: 'word_015', hungarian: 'barát', japanese: '友達' },
  { id: 'word_016', hungarian: 'enni', japanese: '食べる' },
  { id: 'word_017', hungarian: 'inni', japanese: '飲む' },
  { id: 'word_018', hungarian: 'látni', japanese: '見る' },
  { id: 'word_019', hungarian: 'menni', japanese: '行く' },
  { id: 'word_020', hungarian: 'jönni', japanese: '来る' },
  { id: 'word_021', hungarian: 'család', japanese: '家族' },
  { id: 'word_022', hungarian: 'apa', japanese: '父' },
  { id: 'word_023', hungarian: 'anya', japanese: '母' },
  { id: 'word_024', hungarian: 'fiú', japanese: '男の子/息子' },
  { id: 'word_025', hungarian: 'lány', japanese: '女の子/娘' },
  { id: 'word_026', hungarian: 'testvér', japanese: '兄弟姉妹' },
  { id: 'word_027', hungarian: 'nagy', japanese: '大きい' },
  { id: 'word_028', hungarian: 'kicsi', japanese: '小さい' },
  { id: 'word_029', hungarian: 'jó', japanese: '良い' },
  { id: 'word_030', hungarian: 'rossz', japanese: '悪い' },
  { id: 'word_031', hungarian: 'szép', japanese: '美しい' },
  { id: 'word_032', hungarian: 'csúnya', japanese: '醜い' },
  { id: 'word_033', hungarian: 'olcsó', japanese: '安い' },
  { id: 'word_034', hungarian: 'drága', japanese: '高い' },
  { id: 'word_035', hungarian: 'hideg', japanese: '冷たい/寒い' },
  { id: 'word_036', hungarian: 'meleg', japanese: '温かい/暑い' },
  { id: 'word_037', hungarian: 'reggel', japanese: '朝' },
  { id: 'word_038', hungarian: 'este', japanese: '夜' },
  { id: 'word_039', hungarian: 'nap', japanese: '日/太陽' },
  { id: 'word_040', hungarian: 'hét', japanese: '週' },
  { id: 'word_041', hungarian: 'hónap', japanese: '月' },
  { id: 'word_042', hungarian: 'év', japanese: '年' },
  { id: 'word_043', hungarian: 'tegnap', japanese: '昨日' },
  { id: 'word_044', hungarian: 'ma', japanese: '今日' },
  { id: 'word_045', hungarian: 'holnap', japanese: '明日' },
  { id: 'word_046', hungarian: 'reggeli', japanese: '朝食' },
  { id: 'word_047', hungarian: 'ebéd', japanese: '昼食' },
  { id: 'word_048', hungarian: 'vacsora', japanese: '夕食' },
  { id: 'word_049', hungarian: 'étterem', japanese: 'レストラン' },
  { id: 'word_050', hungarian: 'bolt', japanese: 'お店' },
];

// SM-2 Algorithm Constants
export const INITIAL_EASINESS = 2.5;
export const MIN_EASINESS = 1.3;
export const CORRECT_ANSWER_THRESHOLD = 3; // Grade 3-5 is correct
export const LEARNING_INTERVALS = [1, 6]; // in days for the first two correct repetitions
