
import { Word } from './types';

export const INITIAL_WORDS: Word[] = [
  { id: 'word_001', hungarian: 'alma', japanese: 'りんご', example: { sentence: 'Az alma piros.', translation: 'そのリンゴは赤いです。' } },
  { id: 'word_002', hungarian: 'kutya', japanese: '犬', example: { sentence: 'A kutya ugat.', translation: '犬が吠えています。' } },
  { id: 'word_003', hungarian: 'ház', japanese: '家', example: { sentence: 'Ez egy nagy ház.', translation: 'これは大きな家です。' } },
  { id: 'word_004', hungarian: 'könyv', japanese: '本', example: { sentence: 'Olvasok egy könyvet.', translation: '私は本を読んでいます。' } },
  { id: 'word_005', hungarian: 'asztal', japanese: 'テーブル', example: { sentence: 'A könyv az asztalon van.', translation: '本はテーブルの上にあります。' } },
  { id: 'word_006', hungarian: 'szék', japanese: '椅子' },
  { id: 'word_007', hungarian: 'víz', japanese: '水' },
  { id: 'word_008', hungarian: 'kenyér', japanese: 'パン' },
  { id: 'word_009', hungarian: 'autó', japanese: '車' },
  { id: 'word_010', hungarian: 'város', japanese: '街' },
  { id: 'word_011', hungarian: 'utca', japanese: '通り' },
  { id: 'word_012', hungarian: 'iskola', japanese: '学校' },
  { id: 'word_013', hungarian: 'tanuló', japanese: '学生' },
  { id: 'word_014', hungarian: 'tanár', japanese: '先生' },
  { id: 'word_015', hungarian: 'barát', japanese: '友達' },
  { id: 'word_016', hungarian: 'enni', japanese: '食べる' },
  { id: 'word_017', hungarian: 'inni', japanese: '飲む' },
  { id: 'word_018', hungarian: 'látni', japanese: '見る' },
  { id: 'word_019', hungarian: 'menni', japanese: '行く' },
  { id: 'word_020', hungarian: 'jönni', japanese: '来る' },
  { id: 'word_021', hungarian: 'család', japanese: '家族' },
  { id: 'word_022', hungarian: 'apa', japanese: '父' },
  { id: 'word_023', hungarian: 'anya', japanese: '母' },
  { id: 'word_024', hungarian: 'fiú', japanese: '男の子/息子' },
  { id: 'word_025', hungarian: 'lány', japanese: '女の子/娘' },
  { id: 'word_026', hungarian: 'testvér', japanese: '兄弟姉妹' },
  { id: 'word_027', hungarian: 'nagy', japanese: '大きい' },
  { id: 'word_028', hungarian: 'kicsi', japanese: '小さい' },
  { id: 'word_029', hungarian: 'jó', japanese: '良い' },
  { id: 'word_030', hungarian: 'rossz', japanese: '悪い' },
  { id: 'word_031', hungarian: 'szép', japanese: '美しい' },
  { id: 'word_032', hungarian: 'csúnya', japanese: '醜い' },
  { id: 'word_033', hungarian: 'olcsó', japanese: '安い' },
  { id: 'word_034', hungarian: 'drága', japanese: '高い' },
  { id: 'word_035', hungarian: 'hideg', japanese: '冷たい/寒い' },
  { id: 'word_036', hungarian: 'meleg', japanese: '温かい/暑い' },
  { id: 'word_037', hungarian: 'reggel', japanese: '朝' },
  { id: 'word_038', hungarian: 'este', japanese: '夜' },
  { id: 'word_039', hungarian: 'nap', japanese: '日/太陽' },
  { id: 'word_040', hungarian: 'hét', japanese: '週' },
  { id: 'word_041', hungarian: 'hónap', japanese: '月' },
  { id: 'word_042', hungarian: 'év', japanese: '年' },
  { id: 'word_043', hungarian: 'tegnap', japanese: '昨日' },
  { id: 'word_044', hungarian: 'ma', japanese: '今日' },
  { id: 'word_045', hungarian: 'holnap', japanese: '明日' },
  { id: 'word_046', hungarian: 'reggeli', japanese: '朝食' },
  { id: 'word_047', hungarian: 'ebéd', japanese: '昼食' },
  { id: 'word_048', hungarian: 'vacsora', japanese: '夕食' },
  { id: 'word_049', hungarian: 'étterem', japanese: 'レストラン' },
  { id: 'word_050', hungarian: 'bolt', japanese: 'お店' },
  { id: 'word_051', hungarian: 'tapasztalat', japanese: '経験', example: { sentence: 'Sok tapasztalatom van ebben a munkában.', translation: 'この仕事にはたくさんの経験があります。' } },
  { id: 'word_052', hungarian: 'vélemény', japanese: '意見', example: { sentence: 'Mi a véleményed erről a könyvről?', translation: 'この本についてどう思いますか？' } },
  { id: 'word_053', hungarian: 'lehetőség', japanese: '機会/可能性', example: { sentence: 'Ez egy nagyszerű lehetőség számunkra.', translation: 'これは私たちにとって素晴らしい機会です。' } },
  { id: 'word_054', hungarian: 'fontos', japanese: '重要な', example: { sentence: 'Nagyon fontos az egészség.', translation: '健康はとても重要です。' } },
  { id: 'word_055', hungarian: 'gondol', japanese: '考える/思う', example: { sentence: 'Sokat gondolok a jövőre.', translation: '将来のことをよく考えます。' } },
  { id: 'word_056', hungarian: 'dönt', japanese: '決める', example: { sentence: 'Nehéz volt dönteni.', translation: '決めるのは難しかったです。' } },
  { id: 'word_057', hungarian: 'hasznos', japanese: '役に立つ', example: { sentence: 'Ez az információ nagyon hasznos.', translation: 'この情報はとても役に立ちます。' } },
  { id: 'word_058', hungarian: 'érdekes', japanese: '興味深い', example: { sentence: 'Ez egy érdekes történet.', translation: 'これは興味深い話です。' } },
  { id: 'word_059', hungarian: 'különbség', japanese: '違い', example: { sentence: 'Mi a különbség a két autó között?', translation: '2台の車の間にはどんな違いがありますか？' } },
  { id: 'word_060', hungarian: 'fejleszt', japanese: '改善する/向上させる', example: { sentence: 'Fejlesztenem kell a nyelvtudásomat.', translation: '語学力を向上させる必要があります。' } },
  { id: 'word_061', hungarian: 'például', japanese: '例えば', example: { sentence: 'Szeretem a gyümölcsöket, például az almát.', translation: '果物が好きです、例えばリンゴなど。' } },
  { id: 'word_062', hungarian: 'általában', japanese: 'たいてい/通常', example: { sentence: 'Általában hétkor kelek.', translation: '普段は7時に起きます。' } },
  { id: 'word_063', hungarian: 'egyetért', japanese: '同意する', example: { sentence: 'Teljesen egyetértek veled.', translation: 'あなたに完全に同意します。' } },
  { id: 'word_064', hungarian: 'javasol', japanese: '提案する', example: { sentence: 'Mit javasolsz vacsorára?', translation: '夕食に何を提案しますか？' } },
  { id: 'word_065', hungarian: 'megoldás', japanese: '解決策', example: { sentence: 'Meg kell találnunk a legjobb megoldást.', translation: '最善の解決策を見つけなければなりません。' } },
  { id: 'word_066', hungarian: 'egészség', japanese: '健康', example: { sentence: 'Az egészség a legfontosabb.', translation: '健康が一番大切です。' } },
  { id: 'word_067', hungarian: 'kapcsolat', japanese: '関係/つながり', example: { sentence: 'Jó kapcsolatban vagyunk.', translation: '私たちは良い関係にあります。' } },
  { id: 'word_068', hungarian: 'független', japanese: '独立した/自立した', example: { sentence: 'Ő egy független nő.', translation: '彼女は自立した女性です。' } },
  { id: 'word_069', hungarian: 'biztonság', japanese: '安全/セキュリティ', example: { sentence: 'A biztonság az első.', translation: '安全が第一です。' } },
  { id: 'word_070', hungarian: 'környezet', japanese: '環境', example: { sentence: 'Védenünk kell a környezetet.', translation: '私たちは環境を守らなければなりません。' } },
  { id: 'word_071', hungarian: 'feladat', japanese: '課題/タスク', example: { sentence: 'Ez egy nehéz feladat.', translation: 'これは難しい課題です。' } },
  { id: 'word_072', hungarian: 'eredmény', japanese: '結果', example: { sentence: 'Milyen lett az eredmény?', translation: '結果はどうでしたか？' } },
  { id: 'word_073', hungarian: 'szükséges', japanese: '必要な', example: { sentence: 'Minden szükséges eszköz megvan.', translation: '必要な道具はすべて揃っています。' } },
  { id: 'word_074', hungarian: 'külföld', japanese: '外国', example: { sentence: 'Szeretnék külföldön tanulni.', translation: '外国で勉強したいです。' } },
  { id: 'word_075', hungarian: 'felelősség', japanese: '責任', example: { sentence: 'Ez az én felelősségem.', translation: 'これは私の責任です。' } },
];

// SM-2 Algorithm Constants
export const INITIAL_EASINESS = 2.5;
export const MIN_EASINESS = 1.3;
export const CORRECT_ANSWER_THRESHOLD = 3; // Grade 3-5 is correct
export const LEARNING_INTERVALS = [1, 6]; // in days for the first two correct repetitions
